// Copyright 2019 Thomas Brown
// Distributed under the Boost Software License, Version 1.0. (See
// accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)

pipeline {
    agent {
        dockerfile {
            label 'xilinx-vivado-linux'

            registryUrl 'https://docker.inradar.net'
            registryCredentialsId 'radar-docker-registry'
            filename 'Dockerfile'
            args '-v /etc/passwd:/etc/passwd --mount type=tmpfs,destination=/home/azureagent -v /opt/Xilinx:/opt/Xilinx -v /usr/local/share/ca-certificates/inradar-ca.crt:/usr/local/share/ca-certificates/inradar-ca.crt -v /etc/ssl/certs:/etc/ssl/certs -v /etc/ca-certificates.conf:/etc/ca-certificates.conf'
        }
    }

    environment {
        boost_version = '1.71.0'
        XILINXD_LICENSE_FILE = '2100@license-server-0.eastus.inradar.net'
    }

    stages {
        stage('Install Boost') {
            steps {
                sh '''
                boost_version_name=$(echo ${boost_version} | sed 's/\\./_/g')

                mkdir -p lib
                cd lib
                wget -q http://mirrors.inradar.net/yocto/downloads/boost_${boost_version_name}.tar.gz
                tar xfz boost_${boost_version_name}.tar.gz
                cd boost_${boost_version_name}
                ./bootstrap.sh
                '''
            }
        }
        stage('Boost.Build Setup') {
            steps {
                sh '''
                echo "# DO NOT EDIT - generated by Dockerfile" > tmp-user-config.jam
                echo "using asciidoctor ; " >> tmp-user-config.jam
                '''
            }
        }
        stage('Manual') {
            steps {
                /// @todo asciidoctor is not installed
                // sh '''
                // boost_version_name=$(echo ${boost_version} | sed 's/\\./_/g')
                //
                // export BOOST_BUILD_PATH=$(pwd)/lib/boost_${boost_version_name}/tools/build:$(pwd)
                // $(pwd)/lib/boost_${boost_version_name}/b2 --user-config=tmp-user-config.jam
                // '''
                //
                // publishHTML([allowMissing: false,
                //              alwaysLinkToLastBuild: true,
                //              keepAll: false,
                //              reportDir: 'bin/asciidoctor-backend-html5',
                //              reportFiles: 'documentation.html,xsdk.html',
                //              reportName: 'Documentation',
                //              reportTitles: ''])
                sh 'true'
            }
        }
        stage('Documentation') {
            steps {
                sh '''
                boost_version_name=$(echo ${boost_version} | sed 's/\\./_/g')

                export BOOST_BUILD_PATH=$(pwd)/lib/boost_${boost_version_name}/tools/build:$(pwd)
                $(pwd)/lib/boost_${boost_version_name}/b2 --user-config=tmp-user-config.jam --help xsdk
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''#!/bin/bash
                boost_version_name=$(echo ${boost_version} | sed 's/\\./_/g')

                source /opt/Xilinx/SDK/2018.3/settings64.sh
                export BOOST_BUILD_PATH=$(pwd)/lib/boost_${boost_version_name}/tools/build:$(pwd)
                cd test && $(pwd)/../lib/boost_${boost_version_name}/b2 --verbose-test
                '''
            }
        }
    }
}
