= Xilinx SDK (XSDK)

:toc:

== User Manual

== Reference

:leveloffset: +2

= Configuration

[source, jam]
----
import xsdk ;
----

The XSDK tool must be configured as any other Boost.Build tool.  The
tool will automatically detect the location and version of the tool.

[source, jam]
----
using xsdk ;
----

The desired version can be specified.

[source, jam]
----
using xsdk : 2018.3 ;
----

The location can also be specified both with and without a desired
version.

[source, jam]
----
using xsdk : : /opt/Xilinx/SDK/2018.3 ;
----

Note that running with the `--debug-configuration` option to
Boost.Build will print the XSDK location and version as well as the
application templates, operating systems, libraries, and drivers
supported by the version of the tool configured.

= Main Target

This project will add one main target type named `xsdkws`.

[source, jam]
----
xsdkws ( name : sources + : requirements * : default-build * : usage-requirements * )
----

This target will place an application named `app`, several example
applications (`empty_c`, `empty_cpp`, and `hello`), a board-support
packaged named `bsp`, and a hardware definition named `hw` within a
workspace named as defined in the rule, `$(name)`, and provide
`usage-requirements` to users of the named target.

This target will also create several supporting XSCT scripts in the
build directory.

The `print.tcl` script will print out all the available configuration
options for the XSDK Workspace.  This can be useful when developing
the configuration for a project.

The `run.tcl` script take the any compatible program file as an
argument and will run the program.  This script can be used with the
Boost.Build `testing` module as a `<testing.launcher>`.

This target works by creating and running an XSCT script containing
`xsct` commands with values translated from Boost.Build features such
as `<instruction-set>`, `<target-os>`, and others.  Some
representative examples of those `xsct` commands are below.

Create the workspace (`$(build-dir)/$(name).xsdkws`) from the
properties.

[source, tcl]
----
setws $(build-dir)/$(name).xsdkws
----

Generate the hardware definition (`hw`) from the hardware definition
file specified in `$(source)`.

[source, tcl]
----
createhw -name hw -hwspec $(source)
----

Generate and build a board-support package (`bsp`) from the hardware
definition (`hw`), standard Boost.Build features, and free-form
configuration options.

[source, tcl]
----
createbsp -name bsp -proc $(xsdk-instruction-set) -hwproject hw -os $(xsdk-os)

configbsp -bsp bsp sleep_timer psu_ttc_3

updatemss -mss  $ws/bsp/system.mss
regenbsp -bsp bsp

projects -build -type bsp -name bsp
----

Generate and build an application (`app`) which provides a
linker-command file and some options required to properly build an
application.  This defaults to "Empty Application" if
`<xsdk-template>` is not defined.  Neither the application template
nor the application language is required, but can sometimes be useful
to generate a program that can be used as the basis of your program.

The build script will generate several additional applications for
comparison.  Building these application is done as a reference to
debug build issues with programs not built using the XSCT tool as well
as a way to compare the resulting build options.

* `empty_c` - based on the "Empty Application" template for the C language
* `empty_cpp` - based on the "Empty Application" template for the C++ language
* `hello` - based on the "Hello World" or "FreeRTOS Hello World" template for the C language

For example, if `<target-os>` is `elf`, the script generated will be
something like the following.

[source, tcl]
----
createapp -name app       -app {$(xsdk-template)}  -lang $(xsdk-language) -bsp bsp -proc $(xsdk-processor-prefix)_$(xsdk-instruction-set)_$(xsdk-processor-id) -hwproject hw -os $(xsdk-os)
projects -build -type app -name app

createapp -name empty_c   -app {Empty Application} -lang c                -bsp bsp -proc $(xsdk-processor-prefix)_$(xsdk-instruction-set)_$(xsdk-processor-id) -hwproject hw -os $(xsdk-os)
projects -build -type app -name empty_c
createapp -name empty_cpp -app {Empty Application} -lang c++              -bsp bsp -proc $(xsdk-processor-prefix)_$(xsdk-instruction-set)_$(xsdk-processor-id) -hwproject hw -os $(xsdk-os)
projects -build -type app -name empty_cpp
createapp -name hello     -app {Hello World}       -lang c                -bsp bsp -proc $(xsdk-processor-prefix)_$(xsdk-instruction-set)_$(xsdk-processor-id) -hwproject hw -os $(xsdk-os)
projects -build -type app -name hello

----

= Suported FPGA

* Zynq UltraScale+ MPSoC
* Zynq 7000 SoC

= Toolsets

This module supports the processor-specific `gcc` toolsets delivered
within the Xilinx XSDK.

Note that in order to choose the correct toolset, the toolset should
be made conditional on the `instruction-set` in the build system.
One approach for doing this would be to set project requirements in
the Jamroot.  This is required because the `toolset` feature cannot
set in `usage-requirements`.

.`Jamroot`
[source, jam]
----
project
  : requirements
    <instruction-set>cortex-a9:<toolset>gcc-xsdkaarch32
    <instruction-set>cortex-a53:<toolset>gcc-xsdkaarch64

    <instruction-set>cortex-r5:<toolset>gcc-xsdkarmr5

    <instruction-set>microblaze:<toolset>gcc-xsdkmicroblaze
  ;
----

.`project-config.jam`
[source, jam]
----
using xsdk ;

local xsdk-root = [ xsdk.root ] ;

using gcc : xsdkaarch32 : $(xsdk-root)/gnu/aarch32/lin/gcc-arm-none-eabi/bin/arm-none-eabi-g++ ;
using gcc : xsdkaarch64 : $(xsdk-root)/gnu/aarch64/lin/aarch64-none/bin/aarch64-none-elf-g++ ;

using gcc : xsdkarmr5 : $(xsdk-root)/gnu/armr5/lin/gcc-arm-none-eabi/bin/armr5-none-eabi-g++ ;

using gcc : xsdkmicroblaze : $(xsdk-root)/gnu/microblaze/lin/bin/microblaze-xilinx-elf-g++ ;
----

= Boost.Build Features

The following Boost.Build features are used to configure the XSDK.
Workspace.

If Boost.Build does not support a required value for a feature, the
`xsdk` tool will extend the feature with the additional values.

== `<target-os>` - the target operating system

* `elf` - The `standalone` Xilinx operating system.
* `freertos` - The FreeRTOS operating system for Zynq systems.
* `xilkernel` - The Xilinx kernel for Microblaze.

== `<instruction-set>` - the instruction set or processor

The hardware definition file defines which processors are available in
a particular design.  The processors supported by the XSDK are shown
below.

* `cortex-a9` - Cortex-A9
* `cortex-a53` - Cortex-A53
* `cortex-r5` - Cortex-R5
* `microblaze` - Microblaze

= XSDK-related Features

Boost.Build will generally configure the board-support package given
Boost.Build features.  These features can be overridden using the
following toolset flags.

== `xsdk-template`

This feature indicates the application template used to generate the
application.  The application provides the linker script used by
programs built with the XSDK Workspace.

The resulting files can be used to create or update the actual
application code, but are not used when generating programs from the
XSDK Workspace.

This defaults to an empty application.

== `xsdk-language`

This feature indicates the language used for the application and is
only required if the application template requires it.

* `c` (default)
* `c++`

== `xsdk-configuration`

This feature provides information for configuring a board-support
package.  A configuration is a string added to the end of the call to
`configbsp`.

The system will generate the following for each
`<xsdk-configuration>STRING`.

[source, tcl]
----
configbps -bsp bsp STRING
----

== `xsdk-library`

This feature adds Xilinx libraries to the board-support package.
These are the library names as described in the XSDK documentation.

== `xsdk-processor-prefix`

This should be auto-detected by the system.

== `xsdk-processor-id`

This feature assigns the application to run on a particular processor
on the SoC, defaulting to 0.

:leveloffset: -2
